server:
  port: 8001


spring:
  profiles:dev
  application:
    name: xiong-config-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name


eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
